source 'https://rubygems.org'

gem 'bundler'
gem 'rake'
gem 'hanami', '~> 0.9.1'
gem 'spyke'
gem 'puma'
gem 'request_store'
gem 'multi_json'

group :development do
  # Code reloading
  # See: http://hanamirb.org/guides/applications/code-reloading
  gem 'notgun'
  gem 'pry'
end

group :test do
  gem 'rspec'
end
